version: '3'

services:
  viewpoint-db:
    image: postgres:15
    container_name: viewpoint_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "15432:${POSTGRES_PORT}"
    volumes:
      - ./docker/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    command: -p ${POSTGRES_PORT}
      
  viewpoint-backend:
    image: grebennikovas/viewpoint-backend:0.0.1
    build: ./viewpoint-backend
    container_name: viewpoint_backend
    ports:
      - "8081:8081"
    depends_on:
      - viewpoint-db
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://viewpoint-db:${POSTGRES_PORT}/viewpoint
      
  viewpoint-frontend:
    image: grebennikovas/viewpoint-frontend:0.0.1
    build: ./viewpoint-frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules

  viewpoint-nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    depends_on:
      - viewpoint-frontend
      - viewpoint-backend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf:ro
  
  load-samples:
    image: postgres:15
    depends_on:
      - viewpoint-db
    volumes:
      - ./docker/db/load_samples.sh:/docker-entrypoint-initdb.d/load_samples.sh
      - ./docker/db/sample_data.tar:/docker-entrypoint-initdb.d/sample_data.tar
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LOAD_SAMPLES: ${LOAD_SAMPLES}
    command: ["/bin/bash", "-c", "chmod +x /docker-entrypoint-initdb.d/load_samples.sh && /docker-entrypoint-initdb.d/load_samples.sh"]
      
volumes:
  db-data: